2017-05-16 20:59:35,045 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 20:59:35,069 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 20:59:35,069 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 20:59:35,069 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 20:59:35,069 FuncExpansion.py [line: 190] ERROR: Exception, 'Test' object has no attribute 'driver'
2017-05-16 20:59:35,069 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 20:59:35,069 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:21:35,276 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:21:35,298 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:21:35,298 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 21:21:35,298 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:21:35,298 FuncExpansion.py [line: 190] ERROR: Exception, 'Test' object has no attribute 'driver'
2017-05-16 21:21:35,299 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:21:35,299 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:24:57,279 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:24:57,288 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:24:57,288 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 21:24:57,288 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:24:57,288 FuncExpansion.py [line: 190] ERROR: Exception, 'session_id'
2017-05-16 21:24:57,289 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:24:57,289 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:30:11,213 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:30:11,226 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:30:11,226 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 21:30:11,226 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:30:11,226 FuncExpansion.py [line: 190] ERROR: Exception, 'session_id'
2017-05-16 21:30:11,226 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:30:11,229 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:31:24,538 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:31:24,546 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:31:24,546 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 21:31:24,546 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:31:24,546 FuncExpansion.py [line: 190] ERROR: Exception, 'session_id'
2017-05-16 21:31:24,546 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:31:24,549 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:32:40,407 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:32:40,415 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:32:40,415 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 21:32:40,417 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:32:40,417 FuncExpansion.py [line: 190] ERROR: Exception, 'session_id'
2017-05-16 21:32:40,417 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:32:40,418 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:37:36,125 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:37:36,138 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:37:36,138 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 21:37:36,140 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:37:36,140 FuncExpansion.py [line: 190] ERROR: Exception, 'session_id'
2017-05-16 21:37:36,141 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:37:36,142 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:37:54,035 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:37:54,042 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:37:54,042 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 21:37:54,042 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:37:54,042 FuncExpansion.py [line: 190] ERROR: Exception, 'session_id'
2017-05-16 21:37:54,042 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:37:54,045 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:40:17,273 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:40:17,282 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:40:17,282 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 21:40:17,282 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:40:17,282 FuncExpansion.py [line: 190] ERROR: Exception, 'session_id'
2017-05-16 21:40:17,282 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:40:17,283 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:41:59,490 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:41:59,506 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:41:59,506 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 21:41:59,506 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:41:59,507 FuncExpansion.py [line: 190] ERROR: Exception, 'session_id'
2017-05-16 21:41:59,507 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:41:59,510 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:43:43,526 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:43:43,540 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:43:43,542 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 21:43:43,542 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:43:43,542 FuncExpansion.py [line: 190] ERROR: Exception, 'session_id'
2017-05-16 21:43:43,542 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:43:43,545 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:44:02,558 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:44:02,569 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:44:02,569 FuncExpansion.py [line: 167] INFO: 	--> test_login
2017-05-16 21:44:02,569 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:44:02,569 FuncExpansion.py [line: 190] ERROR: Exception, 'session_id'
2017-05-16 21:44:02,569 FuncExpansion.py [line: 192] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:44:02,572 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:48:19,282 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:48:19,289 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:48:19,289 FuncExpansion.py [line: 168] INFO: 	--> test_login
2017-05-16 21:48:19,289 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:48:19,289 FuncExpansion.py [line: 191] ERROR: Exception, 'session_id'
2017-05-16 21:48:19,289 FuncExpansion.py [line: 193] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:48:19,290 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:48:48,779 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:48:48,788 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:48:48,788 FuncExpansion.py [line: 168] INFO: 	--> test_login
2017-05-16 21:48:48,789 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:48:48,789 FuncExpansion.py [line: 191] ERROR: Exception, 'session_id'
2017-05-16 21:48:48,789 FuncExpansion.py [line: 193] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:48:48,790 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:52:05,111 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:52:05,118 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:52:05,118 FuncExpansion.py [line: 168] INFO: 	--> test_login
2017-05-16 21:52:05,119 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:52:05,119 FuncExpansion.py [line: 191] ERROR: Exception, 'session_id'
2017-05-16 21:52:05,119 FuncExpansion.py [line: 193] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:52:05,121 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:54:26,420 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:54:26,427 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:54:26,427 FuncExpansion.py [line: 168] INFO: 	--> test_login
2017-05-16 21:54:26,427 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:54:26,427 FuncExpansion.py [line: 191] ERROR: Exception, 'session_id'
2017-05-16 21:54:26,428 FuncExpansion.py [line: 193] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:54:26,428 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:55:41,913 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:56:17,063 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:56:17,063 FuncExpansion.py [line: 168] INFO: 	--> test_login
2017-05-16 21:56:17,065 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:56:17,611 FuncExpansion.py [line: 191] ERROR: Exception, 'ConfigParser' object has no attribute 'get_option_value'
2017-05-16 21:56:17,611 FuncExpansion.py [line: 193] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:56:18,671 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:57:01,941 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:57:27,592 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:57:27,592 FuncExpansion.py [line: 168] INFO: 	--> test_login
2017-05-16 21:57:27,594 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:57:28,061 FuncExpansion.py [line: 191] ERROR: Exception, 'ConfigParser' object has no attribute 'get_option_value'
2017-05-16 21:57:28,061 FuncExpansion.py [line: 193] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:57:29,150 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:58:07,681 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 21:58:31,825 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 21:58:31,825 FuncExpansion.py [line: 168] INFO: 	--> test_login
2017-05-16 21:58:31,825 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 21:58:32,161 FuncExpansion.py [line: 191] ERROR: Exception, No section: 'user'
2017-05-16 21:58:32,161 FuncExpansion.py [line: 193] ERROR: 	<-- test_login, Exception, Error
2017-05-16 21:58:33,302 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 21:59:39,282 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 22:00:03,558 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 22:00:03,558 FuncExpansion.py [line: 168] INFO: 	--> test_login
2017-05-16 22:00:03,559 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 22:00:05,543 FuncExpansion.py [line: 191] ERROR: Exception, No option 'pwd' in section: 'user'
2017-05-16 22:00:05,543 FuncExpansion.py [line: 193] ERROR: 	<-- test_login, Exception, Error
2017-05-16 22:00:06,562 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 22:03:45,828 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 22:04:12,224 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 22:04:12,226 FuncExpansion.py [line: 168] INFO: 	--> test_login
2017-05-16 22:04:12,226 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 22:04:13,407 FuncExpansion.py [line: 191] ERROR: Exception, No option 'pswd' in section: 'user'
2017-05-16 22:04:13,407 FuncExpansion.py [line: 193] ERROR: 	<-- test_login, Exception, Error
2017-05-16 22:04:14,542 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
2017-05-16 22:05:56,973 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 22:06:09,782 app_gui_init.py [line: 21] INFO: 类初始化。。。
2017-05-16 22:06:35,506 YKJ_func_sample.py [line: 19] INFO: 准备开始测试
2017-05-16 22:06:35,506 FuncExpansion.py [line: 168] INFO: 	--> test_login
2017-05-16 22:06:35,506 YKJ_func_sample.py [line: 35] INFO: 准备开始测试--开始进行登录测试
2017-05-16 22:06:37,099 FuncExpansion.py [line: 191] ERROR: Exception, No option 'pswd' in section: 'user'
2017-05-16 22:06:37,099 FuncExpansion.py [line: 193] ERROR: 	<-- test_login, Exception, Error
2017-05-16 22:06:38,217 YKJ_func_sample.py [line: 25] INFO: 	☜☜☜☜☜测试用例运行结束，开始后续处理☜☜☜☜☜
